Disable LeakyConstantDeclaration
It seems to be impossible to define a cop with an anonymous class, since
`inherited` hook on `RuboCop::Cop::RSpec::Cop` is called before class
body is evaluated, and it's impossible to define class name.

    before do
      fake_cop = Class.new(described_class) do # <- fails here
                   # This never gets called
                   def self.name
                     'RuboCop::RSpec::FakeCop'
                   end

                   def on_send(node)
                     add_offense(node, location: :expression, message: 'I flag everything')
                   end
                 end

      stub_const('RuboCop::RSpec::FakeCop', fake_cop)
    end

    NoMethodError:
      undefined method `split' for nil:NilClass
    # rubocop-rspec/gems/rubocop-0.65.0/lib/rubocop/cop/badge.rb:26:in `for'
    # rubocop-rspec/gems/rubocop-0.65.0/lib/rubocop/cop/cop.rb:60:in `badge'
    # rubocop-rspec/gems/rubocop-0.65.0/lib/rubocop/cop/registry.rb:34:in `enlist'
    # rubocop-rspec/gems/rubocop-0.65.0/lib/rubocop/cop/cop.rb:56:in `inherited'
    # ./lib/rubocop/cop/rspec/cop.rb:54:in `inherited'
    # ./spec/rubocop/cop/rspec/cop_spec.rb:25:in `initialize'
    # ./spec/rubocop/cop/rspec/cop_spec.rb:25:in `new'
    # ./spec/rubocop/cop/rspec/cop_spec.rb:25:in `block (2 levels) in <top (required)>'